version: '3.2'

volumes:
  ssl:
    name: temboard-ssl
    driver: local

services:
  postgres-source-db:
    hostname: postgres-source-db
    container_name: postgres-source-db
    image: postgres-source-db:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEMBOARD_AGENT_VERSION: "8.2.1"
      target: postgres-source-db
    tty: true
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: "5432"
    ports:
      - "6432:5432"
      - "122:22"
      - "3114:2345"
    volumes:
      - type: bind
        source: ./data/postgresql/pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: ./data/postgresql/sshkeys
        target: /tmp/.ssh
    command:
      - "postgres"
      - "-c"
      - "wal_level=hot_standby"
      - "-c"
      - "port=5432"
      - "-c"
      - "hba_file=/var/lib/postgresql/config/pg_hba.conf"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "archive_command=rsync -a %p barman@pg-barman:/backup/barman/postgres-source-db/incoming/%f"
      - "-c"
      - "max_wal_senders=2"
      - "-c"
      - "max_replication_slots=2"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_statement=all"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
      - spectre-network-test

  temboard-repository:
    hostname: repository
    container_name: temboard-repository
    image: postgres:14-bullseye
    profiles:
      - with-temboard
    ports:
      - "6433:5432"
    environment:
      POSTGRES_USER: "temboard"
      POSTGRES_PASSWORD: "temboard"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: "5432"
      POSTGRES_DB: "temboard"
    volumes:
      - type: bind
        source: ./Temboard/server/data/temboard-repository/postgresql/pgdata
        target: /var/lib/postgresql/data
    mem_limit: 1g
    command: >
      postgres -c max_connections=50 -c shared_buffers=256MB -c effective_cache_size=768MB -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=7864kB -c default_statistics_target=500 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=1310kB -c huge_pages=off -c min_wal_size=512MB -c max_wal_size=1GB -c autovacuum=off -c max_worker_processes=2 -c max_parallel_workers_per_gather=2 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=2 -c log_destination='stderr' -c logging_collector=on -c log_directory='/var/lib/postgresql/data/pgdata' -c log_filename='postgresql.log' -c log_min_messages='warning' -c log_min_error_statement='error' -c log_min_duration_statement='0' -c log_duration=on -c log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h %q ' -c log_lock_waits=on -c log_statement='none' -c log_timezone='America/Bahia'
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
      - temboard-network

  temboardui:
    hostname: temboardui
    container_name: temboard-ui
    image: temboard-server:latest
    profiles:
      - with-temboard
    build:
      context: ./Temboard/server
      dockerfile: Dockerfile
      target: temboard-server
      args:
        TEMBOARD_VERSION: "8.2.1"
    ports:
      - "3010:8888"
    depends_on:
      - temboard-repository
    volumes:
      - ssl:/etc/ssl/certs
      - ./Temboard/server/temboard.conf:/home/temboard/temboard.conf:rw
      - type: bind
        source: ./Temboard/server/data/temboard-server/temboard
        target: /home/temboard/temboard
      - type: bind
        source: ./Temboard/server/data/temboard-server/log
        target: /home/temboard/log
    networks:
      - temboard-network
      - spectre-network-test

  pg-barman:
    hostname: pg-barman
    container_name: pg-barman
    image: pg-barman:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: pg-barman
    ports:
      - "222:22"
    depends_on:
      - postgres-source-db
    volumes:
      - type: bind
        source: ./data/pgbarman/backupcfg
        target: /etc/barman.d
      - type: bind
        source: ./data/pgbarman/backups
        target: /backup/barman
      - type: bind
        source: ./data/pgbarman/log
        target: /var/log/barman
      - type: bind
        source: ./data/pgbarman/sshkeys
        target: /tmp/.ssh
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
      - spectre-network-test
    restart: always

networks:
  spectre-network-test:
    name: spectre-network-test
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.19.239.0/24

  temboard-network:
    name: temboard-network
    driver: bridge
